version: '3.7'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: boilerplate-api
    restart: unless-stopped
    depends_on:
      - mysql_db
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
    command:
      - 'yarn'
      - 'start:dev'

  mysql_db:
    container_name: mysql_db
    image: mysql:8.0
    ports:
      - 3307:3306
    restart: on-failure
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: boiler
      MYSQL_USER: boiler
      MYSQL_PASSWORD: boiler
      TZ: Asia/Seoul
